#!/bin/sh
### BEGIN INIT INFO
# Provides:          xshd
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: xshd autologin daemon
# Description:       xshd autologin daemon
### END INIT INFO

. /lib/lsb/init-functions

piddir=/var/run/xshd
pidfile="$piddir"/Xorg

case "$1" in
	start)
		log_daemon_msg "Starting xshd" "xshd"
		mkdir -p "$piddir"

		export DISPLAY=:0

		Xorg -nolisten tcp -noreset $DISPLAY &
		echo "$!" >"$pidfile"

		while ! xset q >/dev/null; do sleep 1; done

		setsid \
			su rob -c \
			'sh ~rob/.xsession &'
		log_end_msg 0
		;;
	stop)
		log_daemon_msg "Stopping xshd" "xshd"
		xargs kill < "$pidfile"
		log_end_msg $?
		;;
	status)
		status_of_proc -p $pidfile /dev/null xshd
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}" >&2
		exit 2
		;;
esac
